<h1>Numpy</h1>

[Numpy](https://numpy.org/doc/stable/user/absolute_beginners.html) is a package containing a myriad of mathematical methods that can easily be implemented in your code or, at the very least, much easier than creating all those methods by hand. As the authors say, numpy is "the fundamental package for scientific computing in Python".<br>

Expect to use Numpy in a daily basis for any roles that involves mathematics for example when creating simulations or processing data as numpy is incredibly powerful to process [arrays](https://www.w3schools.com/python/python_arrays.asp).<br>

First let's import numpy

In [26]:
# How do we import a package again?
import numpy as np

In [28]:
np

<module 'numpy' from '/Users/olivertozer/anaconda3/lib/python3.11/site-packages/numpy/__init__.py'>

In [30]:
# Acessing a single numpy method.
np.add

<ufunc 'add'>

In [32]:
# Using said method
np.add(2,1)

3

It is also possible to import one specific method of a package. For example:

In [34]:
# Can we import only one specific method of a package?
from numpy import add

In [36]:
add(2,1)

3

Is this a good idea?

In [ ]:
add = 1

You can also import all the methods in a package at once:

In [38]:
from numpy import *

Question: which is the best way to import packages? Is there such a thing? <br>

After answering this question let us reset the kernel and pick up from hear to clear our many definitions of numpy above.<br>

Let us start by creating two arrays that we can operate with.

In [40]:
# Reboot the kernal and start running from here.
# Or not! But keep an eye out for possible "interferences".
import numpy as np

In [42]:
# To create a numpy array we pick a list and access the array method from the defined np:
test_array1 = np.array([1,2,3,4,5,6]) # The list itself is the first argument of the function.
test_array2 = np.array([2,2,2,2,2,2])

Question: Can you fit objects of different data types on a numpy array?

In [44]:
test_arrayyyyyy = np.array([1,'Cat',3,4,5,6])

Exercise: slice one of the arrays below to select only a subsection of its elements according to the comments.

In [46]:
# Here are "my" solutions:
test_a1 = np.array([1, 2, 3, 4, 5, 6])
test_a2 = np.array([2, 2, 2, 2, 2, 2])

In [ ]:
# First element of array

# last element of array

# last 3 elements of array

# First 3.

# From index 1 to 3.


Let's have a look at the [documentation](https://numpy.org/doc/stable/reference/generated/numpy.array.html) of these methods and compare with what we discussed about functions. <br>

Then, lets add those two arrays together and see the output.

In [48]:
np.add(test_array1,test_array2)

array([3, 4, 5, 6, 7, 8])

In [50]:
print(test_array1)
print(test_array2)
print(np.add(test_array1,test_array2))

[1 2 3 4 5 6]
[2 2 2 2 2 2]
[3 4 5 6 7 8]


Question: Can you simply use "+" to add those two arrays instead of numpy add?

In [52]:
test_array1+test_array2

array([3, 4, 5, 6, 7, 8])

The same can be done with 2d arrays.

In [ ]:
test_array_2d_1 = np.array([[1,2,3],[4,5,6]])
test_array_2d_2 = np.array([[2,2,2],[2,2,2]])

In [ ]:
np.add(test_array_2d_1, test_array_2d_2)

In [ ]:
print(test_array_2d_1)
print(test_array_2d_2)
print(np.add(test_array_2d_1, test_array_2d_2))

Question: How can you subtract two arrays using numpy?

In [ ]:
np.subtract(test_array_2d_1, test_array_2d_2)

In [ ]:
test_array_2d_1-test_array_2d_2

In [ ]:
np.add(test_array_2d_1, -1*test_array_2d_2)

Question: Will the following operation work? why?

In [ ]:
np.add(test_array1,test_array_2d_1)

Checking the shape of an array can be done in a fairly straightforward way,

In [ ]:
np.shape(test_array_2d_1)

In [ ]:
test_array_2d_1.shape

Question: What will then the following operation do?

In [ ]:
# First ask yourself what is happening here.
100 + test_array1

Arrays can also me multiplied by scalars

In [24]:
np.multiply(test_array1,2)

NameError: name 'np' is not defined

In [ ]:
np.multiply(test_array1,2)*2

In [ ]:
2*test_array1

Or multiplied by each other

In [ ]:
np.multiply(test_array2,test_array1)

In [ ]:
test_array2/test_array1

In [ ]:
np.multiply(test_array2,test_array_2d_1)

Finding where a specific information is in the array can also be incredibly useful as it allows, for example, to filter the data. One way to do this is using [numpy.where](https://numpy.org/doc/stable/reference/generated/numpy.where.html).

In [ ]:
test_array_2d_2

In [ ]:
test_array_2d_2
np.where(test_array_2d_2)

In [ ]:
another_array = np.array([10,20,30,40,50,60])
np.where(another_array > 30)

In [ ]:
another_array[3] = 100

In [ ]:
another_array[3]

Question: what exatcly is the output of the function above used? How can you use it?<br>

Exercise: make a 2d array similar to another_array and run np.where with a condition of your choice. What's the difference in the output?

In [ ]:
another_array1 = np.array([[2,2,2],[1,1,1],[3,3,3]])
another_array2 = np.array([[1,2,5],[3,1,2],[2,6,1]])

In [ ]:
np.where(another_array1 >=3)

In [ ]:
indexes = np.where(another_array1 >=1)

In [ ]:
indexes[0][0]

In [ ]:
another_array1[0,0] = 10

In [ ]:
another_array

In [ ]:
# An example on how to conduct an operation on the elements that satisfy the condition.
np.where(another_array > 30, another_array, another_array*10)

The dot product

In [ ]:
np.dot(test_array_2d_1, test_array_2d_2)

In [ ]:
test_array_2d_3 = np.array([[1,2],[4,5],[3,6]])

In [ ]:
np.shape(test_array_2d_3)

In [ ]:
np.dot(test_array_2d_1, test_array_2d_3)

In [ ]:
np.dot(test_array_2d_1, np.transpose(test_array_2d_2))

In [ ]:
np.shape(np.transpose(test_array_2d_2))

In [ ]:
test_array_2d_1

In [ ]:
np.transpose(test_array_2d_1)

There are many more operations and tools available to use in numpy and this is far from being an extensive review but just an introduction on how to use it. Which packages you will later become more familiar with will vastly depend on your field.

A couple examples of applications will be discussed below.

In [12]:
pwd

'/Users/olivertozer/repos/Python-Module'

In [14]:
import imageio

In [16]:
img = imageio.imread('swans.jpg')

/var/folders/96/hkcg5jn533j7q4c_v0c38w0h0000gn/T/ipykernel_24659/2081515282.py:1: DeprecationWarning: Starting with ImageIO v3 the behavior of this function will switch to that of iio.v3.imread. To keep the current behavior (and make this warning disappear) use `import imageio.v2 as imageio` or call `imageio.v2.imread` directly.
  img = imageio.imread('swans.jpg')


FileNotFoundError: No such file: '/Users/olivertozer/repos/Python-Module/swans.jpg'

In [ ]:
img = imageio.imread("C:\\Users\\andre\\Documents\\Python Scripts\\Bootcamp\\Python\\Swans.jpg")

In [22]:
img

NameError: name 'img' is not defined

In [20]:
np.shape(img)

NameError: name 'np' is not defined

In [18]:
import matplotlib.pyplot as plt

In [ ]:
plt.imshow(img, origin='lower')

In [ ]:
plt.imshow(img)

In [ ]:
type(img)

In [ ]:
img

In [ ]:
np.shape(img)

In [ ]:
plt.imshow(img[:,:,0])

In [6]:
plt.imshow(img)

NameError: name 'img' is not defined

In [ ]:
plt.imshow(img[:,:,0],cmap='hsv')

In [ ]:
plt.imshow(img[:,:,0:1])

In [ ]:
plt.imshow(img[:,:,0:1],cmap='gray')

Exercise: can you slice the picture to include only the swans?

In [ ]:
plt.imshow(img[450:650,275:650,:])

Watch this [video](https://www.youtube.com/watch?v=KuXjwB4LzSA&t=572s) about convolutions. Then lets work with it!

In [ ]:
#Ex from : https://www.kaggle.com/code/valentynsichkar/2d-image-convolution-numpy-tensorflow-keras
# Sobel filter to detect vertical changes on image
f1 = np.array([[1, 0, -1],
               [2, 0, -2],
               [1, 0, -1]])

In [ ]:
from scipy.signal import convolve2d

In [ ]:
convolve2d(img[:,:,0],f1)

In [ ]:
plt.imshow(convolve2d(img[:,:,0],f1))

In [ ]:
fig, axes = plt.subplots(nrows=1, ncols=2, figsize=(10, 6))
axes[0].imshow(img)
axes[1].imshow(convolve2d(img[:,:,0],f1),cmap='gray')
fig.tight_layout()